// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huxsqozfjfjpjjsjmxkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eHNxb3pmamZqcGpqc2pteGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDYwODcsImV4cCI6MjA3MzUyMjA4N30.khtcLGOWt3mjwJEz_cQ2Kwxjf6QhS3EHKPUDEkFKa18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});